### ISSUE TITLE
Can do Kcaptcha?

### ISSUE THREAD

**Issue by rastarr** [nate1911/cnn-models-captcha#1]
Hi, 
I saw your new repo and am interested whether it can do kcaptcha style captchas?
But I have no idea how to go about testing your code yet.

**Comment by nate1911** [comment]
Hi,
The model as of now can do digits only and you can check the styles of the captchas on the link below.
https://www.kaggle.com/datasets/tomtillo/5000-labelled-captcha-for-deeplearning
